# -*- coding: utf-8 -*-
"""Biometric-Customer-Authentication-main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W3SRPWwbMUwuPXVBQXfIQyq8yN1Hs7tL
"""

!git clone https://github.com/NidhiAI/Biometric-Customer-Authentication

!pip install python_speech_features

cd '/content/Biometric-Customer-Authentication'

!python FeatureExtraction.py

!python TrainingModel.py

!python Test.py

!pip install ffmpeg-python

# add new user
file_name = input('Enter your name: ')
print(f'You entered {file_name}')

cd '/content/Biometric-Customer-Authentication/addNewCustomer'

!mkdir {file_name}

pwd

cd '/content/Biometric-Customer-Authentication/addNewCustomer/'{file_name}

pwd

cd '/content/Biometric-Customer-Authentication'

!python RecordAudio.py

from RecordAudio import record
import IPython

filename1 = file_name+'-1'+'.mp3'  #'felixtest.wav'
record(filename1, 5)
IPython.display.Audio(filename1)

filename2 = file_name+'-2'+'.mp3'  #'felixtest.wav'
record(filename2, 5)
IPython.display.Audio(filename2)

filename3 = file_name+'-3'+'.mp3'  #'felixtest.wav'
record(filename3, 5)
IPython.display.Audio(filename3)

filename4 = file_name+'-4'+'.mp3'  #'felixtest.wav'
record(filename4, 5)
IPython.display.Audio(filename4)

filename5 = file_name+'-5'+'.mp3'  #'felixtest.wav'
record(filename5, 5)
IPython.display.Audio(filename5)

import subprocess

subprocess.call(['ffmpeg', '-i', '/content/Biometric-Customer-Authentication/Nidhi_Agarwal_0010-1.mp3', 
                 '/content/Biometric-Customer-Authentication/addNewCustomer/Nidhi_Agarwal_0010/Nidhi_Agarwal_0010-1.wav'])

subprocess.call(['ffmpeg', '-i', '/content/Biometric-Customer-Authentication/Nidhi_Agarwal_0010-2.mp3', 
                 '/content/Biometric-Customer-Authentication/addNewCustomer/Nidhi_Agarwal_0010/Nidhi_Agarwal_0010-2.wav'])


subprocess.call(['ffmpeg', '-i', '/content/Biometric-Customer-Authentication/Nidhi_Agarwal_0010-3.mp3', 
                 '/content/Biometric-Customer-Authentication/addNewCustomer/Nidhi_Agarwal_0010/Nidhi_Agarwal_0010-3.wav'])


subprocess.call(['ffmpeg', '-i', '/content/Biometric-Customer-Authentication/Nidhi_Agarwal_0010-4.mp3', 
                 '/content/Biometric-Customer-Authentication/addNewCustomer/Nidhi_Agarwal_0010/Nidhi_Agarwal_0010-4.wav'])


subprocess.call(['ffmpeg', '-i', '/content/Biometric-Customer-Authentication/Nidhi_Agarwal_0010-5.mp3', 
                 '/content/Biometric-Customer-Authentication/addNewCustomer/Nidhi_Agarwal_0010/Nidhi_Agarwal_0010-5.wav'])

pwd

# Write line to file

with open('addUserTrain.txt', 'w') as writefile:
    writefile.write(file_name+'/'+filename1.split(".")[0]+'.wav'+'\n')
    writefile.write(file_name+'/'+filename2.split(".")[0]+'.wav'+'\n')
    writefile.write(file_name+'/'+filename3.split(".")[0]+'.wav'+'\n')
    writefile.write(file_name+'/'+filename4.split(".")[0]+'.wav'+'\n')
    writefile.write(file_name+'/'+filename5.split(".")[0]+'.wav')
#    writefile.write(file_name+'/'+filename5+'\n')
#    writefile.write(file_name+'/'+filename6+'\n')
#    writefile.write(file_name+'/'+filename7+'\n')
#    writefile.write(file_name+'/'+filename8+'\n')
#    writefile.write(file_name+'/'+filename9+'\n')
#    writefile.write(file_name+'/'+filename10+'\n')

import shutil

shutil.copy('/content/Biometric-Customer-Authentication/addUserTrain.txt', 
                 '/content/Biometric-Customer-Authentication/addNewCustomer/Nidhi_Agarwal_0010/addUserTrain.txt')

!python addNewUserTrain.py Nidhi_Agarwal_0010

# Now do testing for new user 

filename11 = file_name+'-11'+'.mp3'  #'felixtest.wav'
record(filename11, 5)
IPython.display.Audio(filename11)

subprocess.call(['ffmpeg', '-i', '/content/Biometric-Customer-Authentication/Nidhi_Agarwal_0010-11.mp3', 
                 '/content/Biometric-Customer-Authentication/testData/Nidhi_Agarwal_0010-11.wav'])

pwd

# append new test line to file

with open("/content/Biometric-Customer-Authentication/testDataPath.txt", "a") as myfile:
    myfile.write("\nNidhi_Agarwal_0010-11.wav")

!python Test.py

!python Test.py

